---
language: node_js
node_js:
  - "8.0.0"

sudo: false

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false
  - npm install lerna

install:
  - lerna bootstrap

script:
  - npm test
